# .travis.yml for cpuaff
#
# See eg http://docs.travis-ci.com/user/languages/cpp/
#
# This is much simplified (rake-free) version of the example at 
# https://github.com/rubinius/rubinius/blob/master/.travis.yml
#
# Dirk Eddelbuettel, 31 Jan 2015

language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update && sudo apt-get install -y qtbase5-dev qt5-default qttools5-dev-tools
  - sudo apt-get install -y libboost-all-dev
  - if [ $CXX == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update -qq; fi
  - if [ $CXX == "g++" ]; then export QMAKE_COMMAND="qmake QMAKE_CXX=g++-4.9"; fi
  - if [ $CXX == "clang++" ]; then export QMAKE_COMMAND="qmake -spec linux-clang"; fi

install:
  - sudo apt-get install g++-4.9; export CXX="g++-4.9"

script:
  - $QMAKE_COMMAND
  - make
  - pushd examples/cpumonitor
  - $QMAKE_COMMAND
  - make
  - popd
  - pushd examples/distribution
  - $QMAKE_COMMAND
  - make
  - popd

notifications:
  email:
    on_success: change
    on_failure: change

os:
  - linux

