# .travis.yml for cpuaff
#
# See eg http://docs.travis-ci.com/user/languages/cpp/
#
# This is much simplified (rake-free) version of the example at 
# https://github.com/rubinius/rubinius/blob/master/.travis.yml
#
# Dirk Eddelbuettel, 31 Jan 2015

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - sudo apt-get update && sudo apt-get install -y qt5-qmake qt5-default

install:
  - if [ $CXX == g++ ]; then sudo apt-get install g++-4.9; export CXX="g++-4.9"; fi

script: 
  - qmake && make

notifications:
  email:
    on_success: change
    on_failure: change

os:
  - linux

